### ISSUE TITLE
Allow fuser to load arbitrary filesystems (such as "memfs")

### ISSUE THREAD

**Issue by cunidev** [ls1-sys-prog-course/task2-fileio#1]
I think there is a bug with `allow_other` being disabled, as seen in the CI logs:
```
  fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
```

On my private machine, I had to go to `/etc/fuse.conf` and enable it. Thanks in advance

**Comment by cunidev** [comment]
Example log: https://github.com/ls1-sys-prog-course/task2-fileio-cunidev/runs/6369993577?check_suite_focus=true

**Comment by Mic92** [comment]
Is it possible to disable the allow-other option in the fuse application or in the tests?
It should not be needed.

**Comment by cunidev** [comment]
Found the issue: That was a side effect of enabling `MountOption::AutoUnmount`, which is not strictly needed for this (just helps to avoid unmounting it manually later)
